apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-cd-cert
spec:
  secretName: argocd-tls
  issuerRef:
    name: argo-cd-issuer
    kind: Issuer
  commonName: argocd.localtest.me
  dnsNames:
  - argocd.localtest.me
