apiVersion: operators.grafana.com/v1alpha1
kind: Grafana
metadata:
  name: example-grafana
  namespace: operators
spec:
  config:
    log:
      mode: "console"
      level: "info"
  ingress:
    enabled: false
  deployment:
    replicas: 1
