apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: argo-logs
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: "k8s"
spec:
  tail:
    # Captures logs from:
    # - Argo CD (argocd namespace)
    # - Argo Workflows (argo namespace)
    # - Argo Events (workflow-playground namespace)
    path: /var/log/containers/*_argo_*.log,/var/log/containers/*_argocd_*.log,/var/log/containers/*_workflow-playground_*.log
    pathKey: filename
    tag: kube.*
    parser: docker
    refreshIntervalSeconds: 10
    memBufLimit: 5MB
    skipLongLines: true
    db: /fluent-bit/tail/argo-logs.db
