---
apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
  name: argo-logs-to-opensearch
  labels:
    strimzi.io/cluster: opensearch-connect
spec:
  class: io.aiven.kafka.connect.opensearch.OpensearchSinkConnector
  tasksMax: 1
  config:
    topics: argo-logs
    connection.url: https://opensearch-cluster-client.logging.svc:9200
    connection.username: admin
    connection.password: changeme
    type.name: _doc
    key.ignore: true
    schema.ignore: true
