---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: argo-logs
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
    segment.ms: 3600000
    segment.bytes: 536870912
