---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: argo-logs-to-opensearch
  labels:
    strimzi.io/cluster: opensearch-connect
spec:
  class: com.amazon.opensearch.kafka.connect.OpensearchSinkConnector
  tasksMax: 1
  config:
    topics: argo-logs
    connection.url: https://opensearch-cluster-client.logging.svc:9200
    connection.username: admin
    connection.password: changeme
    type.name: _doc
    key.ignore: true
    schema.ignore: true
    behavior.on.malformed.documents: ignore
    drop.invalid.message: true
    write.method: bulk
    batch.size: 2000
    max.in.flight.requests: 5
    flush.timeout.ms: 60000
    linger.ms: 2000
    index: argo-logs-%{+YYYY.MM.dd}
    index.rotation.strategy: interval
    index.rotation.interval.ms: 86400000
    index.timezone: UTC
