---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: strimzi-operator-ns-access
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: strimzi-operator-ns-access
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: strimzi-operator-ns-access
subjects:
  - kind: ServiceAccount
    name: strimzi-cluster-operator
    namespace: kube-system
