site_name: Platform CDK8s Developer Documentation
site_description: Developer documentation for the Containerly Platform CDK8s project
site_url: https://containerly.github.io/platform/
repo_url: https://github.com/containerly/platform
repo_name: containerly/platform

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - Development: development.md
  - Contributing: contributing.md
  - Operations: operations.md
  - Version Management: version-management.md
  - Troubleshooting: troubleshooting.md
  - API Reference: api-reference.md
  - Flux:
    - Custom Resources: flux/flux-crs.md
  - Observability:
    - Prometheus Operator CRs: observability/prometheus-operator-crs.md

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
