apiVersion: v1
kind: Service
metadata:
  name: vmselect-vmcluster
  namespace: operators
spec:
  ports:
    - name: vmselect-http
      port: 8428
      targetPort: 8428
  selector:
    app.kubernetes.io/name: vmselect
