---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: opensearch-initial-admin-password
  namespace: default
spec:
  encryptedData:
    # ChangeMe_123!
    OPENSEARCH_INITIAL_ADMIN_PASSWORD: AgCvnJnJOKKN4J/MJGV692jnpFkmz02lTi0TKtjnWzReQWMEfV8FjJkL0w40odvIzRG860uuTGyZCKoAkeMVfajD1UGmBcl5UbY6LFMjtoOmMzGXG8VdgN7Ixs+KRiMogczIQq7dudBHgirho1cpqgC7kt/YfpzJUbLH4updqVIDZwY24YaT6okHuFqSXz7Ne+3iTY7NHlImBKdr8qsJOCH35qmC8eZ+xapWna2X30E35PCNqtcmF1gplQ3TWXIuzBP8paoDmcDr8cwW6ylp0xx1/UcJfHMv//9FXyHtLQap8qkafbGEEAFSqgRpDXorJx/fhZbYkoGquO53YqTkE+dD8BUeHgjnpx/bAy0hrynSB5uAQ3Jf4sQg7tVmUO8en5qcWfDZvVlJOJ8uyNVbNwhlDT8Vq3HrXr2YWFSJFh/9Y/IGIswrlLdy/nmVduSf1ipRHOwrBU8KpijagGn39VGL8JGPOb4ylk94GJLvUYD87U8nTucvkIayE7oKVt8aOhG4osbvft8i7/xhJQIxDz9QvFNQz45RV039vJTJQH1w+HgqKT505i3DUwPjc398f+wkxrTh2RuBIuvH3JuLsge1aNeQNZksMP0hxLtTyGuwtYhR1G+3ikbmz3GRdhxlsXiXIu0rDtrp3f2JGYIEZQzxS/kmbRfROf1S7wH9YjNvjxXEj6jdS2qhj1PPvCx+X5iuuSJFMBuKqnQ+afx1
  template:
    metadata:
      name: opensearch-initial-admin-password
      namespace: default
    type: Opaque
---
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-first-cluster
  namespace: default
spec:
  general:
    serviceName: my-first-cluster
    version: "3"
  dashboards:
    enable: true
    version: "3"
    replicas: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "200m"
  nodePools:
    - component: masters
      replicas: 3
      resources:
         requests:
            memory: "4Gi"
            cpu: "1000m"
         limits:
            memory: "4Gi"
            cpu: "1000m"
      roles:
        - "data"
        - "cluster_manager"
      persistence:
         emptyDir: {}
      env:
        - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
          value: "Password9!"
