# Simple OpenSearch cluster for log storage (UNSECURED - dev only!)
# Deploy this when you're ready to start storing logs in OpenSearch
# kubectl apply -f opensearch-cluster.yaml
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
  namespace: logging
spec:
  general:
    serviceName: opensearch-cluster
    version: 2.11.1
    httpPort: 9200
    setVMMaxMapCount: true
  dashboards:
    enable: true
    version: 2.11.1
    replicas: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "200m"
  bootstrap:
    env:
      - name: DISABLE_INSTALL_DEMO_CONFIG
        value: "true"
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "5Gi"
      persistence:
        emptyDir: {}
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "500m"
      roles:
        - "cluster_manager"
        - "data"
      env:
        - name: DISABLE_INSTALL_DEMO_CONFIG
          value: "true"
  security:
    disable: true
    tls:
      http:
        enabled: false
      transport:
        enabled: false
