# Simple OpenSearch cluster for log storage (UNSECURED - dev only!)
# Deploy this when you're ready to start storing logs in OpenSearch
# kubectl apply -f opensearch-cluster.yaml
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
  namespace: logging
spec:
  general:
    serviceName: opensearch-cluster
    version: 2.11.1
    httpPort: 9200
    setVMMaxMapCount: true
    additionalConfig:
      plugins.security.disabled: "true"
      plugins.security.ssl.transport.enabled: "false"
      plugins.security.ssl.http.enabled: "false"
  dashboards:
    enable: true
    version: 2.11.1
    replicas: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "200m"
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "5Gi"
      persistence:
        emptyDir: {}
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "500m"
      roles:
        - "cluster_manager"
        - "data"
      env:
        - name: DISABLE_INSTALL_DEMO_CONFIG
          value: "true"
      additionalConfig:
        plugins.security.disabled: "true"
        plugins.security.ssl.transport.enabled: "false"
        plugins.security.ssl.http.enabled: "false"
      probes:
        readiness:
          command:
            - /bin/bash
            - -c
            - curl --silent --fail http://localhost:9200/_cluster/health || exit 1
          initialDelaySeconds: 60
          periodSeconds: 30
