---
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-first-cluster
  namespace: default
spec:
  general:
    serviceName: my-first-cluster
    version: "3"
  bootstrap:
    env:
      - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
        value: "Password9!"
  dashboards:
    enable: true
    version: "3"
    replicas: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "200m"
  nodePools:
    - component: masters
      replicas: 3
      resources:
         requests:
            memory: "4Gi"
            cpu: "1000m"
         limits:
            memory: "4Gi"
            cpu: "1000m"
      roles:
        - "data"
        - "cluster_manager"
      persistence:
         emptyDir: {}
      env:
        - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
          value: "Password9!"
    - component: nodes
      replicas: 1
      roles:
        - "data"
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "500m"
      env:
        - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
          value: "Password9!"

