---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docker-registry-config
  namespace: workflow-playground
spec:
  encryptedData:
    config.json: AgCuqXrHLwmO4FyHJw1wdriG8D82hVF3LJyUIJstUxSztVJNLtFrGylNfjBqtj72kZIwvSngUlsXLe7bsbxIWkrrnh83c86UKbO6I+uq2DJO0bxB1VorjV2QbJJIk7CbN7xqWipDBv9WyNvc4moRRDdmOWd7MHGb0eUFMUgOWsZo4Gb0IFMdm0V4cuy7JQJNbxkue36vwQlOTOSnJJ7LBj1g9Tlb6lJVs667WwBvln6yQKfU9vgKsrwvoz/qYEGuO6+iG4yTMxJxb2BdbhFxfFEtR7RvfUYgoYyoxvNwhojUH4ch6kHyOB5AyHzIrEjz0gNR2Prh5IqR/+XRWP4/SNTPE+i8Q/xz5VQ65jqiPz0VmVHL0mL5Jpk0gxw69Z4DJM7eRAd0qkz6sQeqA5jPzP0ah9/7U1alpaEJOwOS2FjU6SXmqClFMk6x/dpBp8qdyJTyAB9NVjmxYPz5r1rRfr2YJpIrI0XbUeC9Zxo+CVBIaRRBAbO3ecmf+MK+Utmy/NoU+eUYspwbQjL+6Zbepw8cP4mMaMNVezIfpK0ckJJxja1MGkljydkCKGAYFriTDpTzmgIF/pige7lpYDD++Ao9Cclkt5Ab3JfSn5lEwuILjJ9CYJYbyJJLtBmHRYretedk6nqnXUBsTgUpucxQTA1mGHwLnHdYeoH/FDbpMtEYjfnwv8SDnFO/NBK9aP5QkIeNUYvGhnyEnPL7ma3juzs8uki+C5ZztfwjVk/Oq39QGaah8eJQOi3D2zKbrQcz+tSPhXd2n6xhF1eEI/gDBBFu7EwJxWTku568GSzOhuaV8v2khC3+l6vzS6SLbNWHIsqXqjUMPI6azxk=
  template:
    metadata:
      name: docker-registry-config
      namespace: workflow-playground


---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: pr-event
      eventSourceName: github
      eventName: internal-repo
      filters:
        data:
          - path: headers.X-Github-Event
            type: string
            value:
              - pull_request
          - path: body.action
            type: string
            value:
              - opened
              - edited
              - reopened
              - synchronize
          - path: body.pull_request.state
            type: string
            value:
              - open
          - path: body.pull_request.base.ref
            type: string
            value:
              - main
  triggers:
    - template:
        name: github-message
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: github-
              spec:
                entrypoint: print-message
                serviceAccountName: operate-workflow-sa
                arguments:
                  parameters:
                    - name: pr-title
                    - name: pr-number
                    - name: short-sha
                templates:
                  - name: print-message
                    inputs:
                      parameters:
                        - name: pr-title
                        - name: pr-number
                        - name: short-sha
                    container:
                      image: busybox
                      command: [echo]
                      args: ["{{inputs.parameters.pr-title}}"]
          parameters:
            - src:
                dependencyName: pr-event
                dataKey: body.pull_request.title
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: pr-event
                dataKey: body.pull_request.number
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: pr-event
                dataTemplate: "{{ .Input.body.pull_request.head.sha | substr 0 7 }}"
              dest: spec.arguments.parameters.2.value
      retryStrategy:
        steps: 3
    - template:
        name: github-docker-build
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: github-docker-build-
                namespace: workflow-playground
              spec:
                serviceAccountName: operate-workflow-sa
                workflowTemplateRef:
                  name: ci-pipeline
                arguments:
                  parameters:
                    - name: repo_url
                    - name: branch
                    - name: dockerfile
                      value: "Dockerfile"
                    - name: context_path
                      value: ""
                    - name: image_name
                      value: ghcr.io/containerly/openapi-ruby-on-rails
                    - name: image_tag
                    - name: test_command
                      value: bundle exec rake test
                    - name: github_username
                      value: containerly
          parameters:
            - src:
                dependencyName: pr-event
                dataTemplate: '{{ if .Input.body.pull_request.head.repo }}{{ .Input.body.pull_request.head.repo.clone_url }}{{ else }}{{ .Input.body.repository.clone_url }}{{ end }}'
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: pr-event
                dataKey: body.pull_request.head.ref
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: pr-event
                dataTemplate: '{{ if .Input.body.pull_request.head.repo }}{{ default "Dockerfile" .Input.body.pull_request.head.repo.dockerfilePath }}{{ else }}Dockerfile{{ end }}'
              dest: spec.arguments.parameters.2.value
            - src:
                dependencyName: pr-event
                dataTemplate: 'pr-{{ .Input.body.pull_request.number }}-{{ .Input.body.pull_request.head.sha | substr 0 7 }}'
              dest: spec.arguments.parameters.5.value
            - src:
                dependencyName: pr-event
                dataTemplate: '{{ default "bundle exec rake test" .Input.body.pull_request.head.repo.testCommand }}'
              dest: spec.arguments.parameters.6.value
      retryStrategy:
        steps: 3
