---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-access
  namespace: workflow-playground
spec:
  encryptedData:
    secret: AgDLlkyY3sHs8PZPbdAGENe2Mv27PsJYlKuofTYaXXz4eJojeEiUjv5RqxDi1fUIUThlPu55/R83+U/bBYcdGsoQ9SZoZmGSBIqsxlrsVi6G12jGze8qtngAA0M3DuvgoEJl8t9X3aQ9gEGHCSKiY6v7Gn+RBVEOIAxKSDuhk7r8cdPlvRq0Y8olW2ZXa1CXGpT5wgadMrNEtn/VMZrHyPm1kA1eSjfNUqs0H6aNAUihIlOIvHVH5uEMPkamvV30UAlK5iIdNtKwtwVtHa5XpSTdZS2laRKgyp8Aj6kA1cU4Uwz5jR9YmTUklht9/9cQ7xDAeK7gPe0gLYCEqH4hzW99OBh8V667UWV88xPSw1d8GyS6uzFJ3FMsPIjomcBzrGJPGHzpKlv0O3BxXa7UeNPpHaTcGsfUa+CF07VzK1XlLh3XCubcWo93nwmMgqtfZcA7WYq+fUFtKSRTxAMb3pSlwyi/phAbB2MRgmh0km4dTFWFZASP96uRSobSDSagGv7TpJg0adgejjILxIcNps3sx4vfNzziH4j/ZHRzpqGlEqqn8CNkXtEACt1i1S6+0L9aFdfpzoaQD/1TK02A+oG8TZA4usZw7pRrHg8qiO/qtiO3M8hMiBhvKYGWxqn7Pmh/q2LPjXeV0b5sWfT5rwEmukgAq+4Fz58ybafAIrPTHutNLpN0MbqM2FcM58mXosvzjM4SXs7XGWaUv+2jpkWmXsjG8D/pbbhCTTI=
    token: AgAO83Sr/j6ug+VKU3LmWsn06bypMO/N8+izXyZ5+XwrCtET9ucV6ynjOJpLVO0uJclrIXI+WO7GomcRI/e3C4BzMMH2nrLclFXV8zgYXKqL/RYTz0U1bbJCP5TO+56x+XTkyyOBmbiEKsO7BUryoYlgQNOH1+Wz3GBdtfpkV4yoLYgA29W9hZvHTE5TrRYyaN5nBXrCVOejqQa4HC6ckch31IBbZq0z43b15YhN6lZr4wMdzVZnSrvq2u356zTA2dwgpdXIfE4inhp/qkGj/VdbTo9tj9JD1AqIwuXcHKzhNSA4S0AmCRvz2wtDsQATBTbbsHpc+1om66CqLZAk4De1VyaZBHWxYMvEtDSrcheeq/9JC4A5kiWjxvzQkwxBJc6VbYcPmM6+T/TsMmUfucqC9H/0ZEYbAFmI45/gfbAkt8s7DZIbXzqAp2Pb+VfIzDKHrUtyhfTDymgXDzUUpd1++NPHxGyhJsfBKfUFAu/eTtgAmuswqlLfPEhQSP1oGhoDybreVFIylEUGb67LN4cX6nSH3iG3jEA9j+t2roUwc1SdMg+Wzqlhe4VgknNkBgRpwcmFQ2sGENMwgXGC4D3D565ISjYXDJw755Q3FvmOd1S7MTqhE8IptKMDimDVutAhm1f61aKxYlZpMAP6hZEH7JsL0Uo0gWEeBFGCk+LpmODrXR+04Xc4qQ3YsSltKw4zZdU0QtUG1DgW7cPpTOExRPaLcp6HbfpyIVD2Lz/heAl4orWeGcCbALzHBS/fchqYdKmlwdavjg7Qb7Y+bYLBNIeUYd1rkSYpcE/iHn9AnY0p7RnTJYHZoeaFE6Y=
  template:
    metadata:
      name: github-access
      namespace: workflow-playground
    type: Opaque

---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
spec:
  service:
    ports:
      - name: internal-repo
        port: 12000
        targetPort: 12000
  github:
    internal-repo:
      repositories:
        - owner: containerly
          names:
            - openapi-ruby-on-rails
      webhook:
        endpoint: /push
        port: "12000"
        method: POST
        url: https://argo-events.internal.example.com/push
      events:
        - push
        - pull_request
      apiToken:
        name: github-access
        key: token
      webhookSecret:
        name: github-access
        key: secret
      insecure: false
      active: true
      contentType: json
