apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example
  namespace: workflow-playground
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: secret-to-be-created
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .provider_key.AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .provider_key.AWS_SECRET_ACCESS_KEY }}"
  # Expect the AWS Secrets Manager secret `provider-key` to contain JSON keys:
  #   {
  #     "AWS_ACCESS_KEY_ID": "...",
  #     "AWS_SECRET_ACCESS_KEY": "..."
  #   }
  dataFrom:
  - extract:
      key: provider-key
