apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example
  namespace: workflow-playground
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: secret-to-be-created
    creationPolicy: Owner
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: provider-key
      property: AWS_ACCESS_KEY_ID
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: provider-key
      property: AWS_SECRET_ACCESS_KEY
  # Expect the AWS Secrets Manager secret `provider-key` to contain JSON keys:
  #   {
  #     "AWS_ACCESS_KEY_ID": "...",
  #     "AWS_SECRET_ACCESS_KEY": "..."
  #   }
