apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example
  namespace: workflow-playground
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: secret-to-be-created
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .providerkey | fromJson | dig \"AWS_ACCESS_KEY_ID\" \"\" }}"
        AWS_SECRET_ACCESS_KEY: "{{ .providerkey | fromJson | dig \"AWS_SECRET_ACCESS_KEY\" \"\" }}"
  # AWS Secrets Manager secret `provider-key` should contain JSON:
  #   {"AWS_ACCESS_KEY_ID": "...", "AWS_SECRET_ACCESS_KEY": "..."}
  data:
  - secretKey: providerkey
    remoteRef:
      key: provider-key
