apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example
  namespace: workflow-playground
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: secret-to-be-created
    creationPolicy: Owner
  # AWS Secrets Manager secret `provider-key` should contain JSON:
  #   {"AWS_ACCESS_KEY_ID": "...", "AWS_SECRET_ACCESS_KEY": "..."}
  # The extract below will parse the JSON and create a key for each property
  dataFrom:
  - extract:
      key: provider-key
      conversionStrategy: Default
      decodingStrategy: None
