apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: openapi-server-spring
  labels:
    app: openapi-server-spring
spec:
  instanceSelector:
    matchLabels:
      dashboards: openapi-server-spring
  title: OpenAPI Server Spring
