apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: openapi-server-spring
  labels:
    app: openapi-server-spring
spec:
  datasource:
    access: proxy
    isDefault: true
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
    name: prometheus
    type: prometheus
    url: 'http://prometheus-service:9090'
  instanceSelector:
    matchLabels:
      dashboards: openapi-server-spring
  plugins:
    - name: grafana-clock-panel
      version: 1.3.0
