apiVersion: opensearch.opensearch.org/v1
kind: OpenSearchCluster
metadata:
  name: example
  namespace: opensearch
spec:
  general:
    serviceName: example
    version: 2.19.2
  nodePools:
    - component: masters
      replicas: 3
      roles:
        - cluster_manager
        - ingest
        - data
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "500m"
      persistence:
        emptyDir: {}
  # For production use, configure persistence:
  # persistence:
  #   pvc:
  #     storageClass: "standard"
  #     accessModes:
  #       - ReadWriteOnce
  #     resources:
  #       requests:
  #         storage: 50Gi
