
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: example
  namespace: operators
spec:
  replicas: 1
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchLabels:
      release: example
  serviceMonitorNamespaceSelector:
    matchNames:
      - "default"
  ruleSelector:
    matchLabels:
      release: example
  podMonitorSelector: {}
  probeSelector: {}
  alerting:
    alertmanagers:
      - namespace: operators
        name: alertmanager-main
        port: web
