apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoria-metrics-datasource
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: victoria-metrics
    type: prometheus
    access: proxy
    url: http://victoria-metrics:8428
    isDefault: true
    jsonData:
      "tlsSkipVerify": true
      "timeInterval": "5s"
