apiVersion: v1
data:
  application.resourceTrackingMethod: annotation
  admin.enabled: 'false'
  statusbadge.enabled: 'true'
  users.anonymous.enabled: 'true'
  ga.trackingid: 'UA-105170809-6'
  url: https://53cc6c0932dd.ngrok-free.app
  configManagementPlugins: |
    - name: flux
      generate:
        command: [sh, -c]
        args: ["argocd-flux-plugin . --path $GIT_PATH"]
  accounts.anonymous.enabled: 'true'
  dex.config: ''
kind: ConfigMap
metadata:
  name: argocd-cm
