---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openapi-server-spring
  labels:
    app: openapi-server-spring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openapi-server-spring
  template:
    metadata:
      labels:
        app: openapi-server-spring
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
      - name: openapi-server-spring
        image: ghcr.io/containerly/openapi-server-spring:latest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: SPRING_CONFIG_LOCATION
          value: "classpath:/application.yaml,/etc/config/application.yaml"
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: config
        configMap:
          name: openapi-server-spring-config
      securityContext:
        fsGroup: 1000
