apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: openapi-server-spring
  labels:
    app.kubernetes.io/name: openapi-server-spring
spec:
  interval: 1m
  ref:
    branch: main
  url: 'https://github.com/containerly/openapi-server-spring'
  secretRef:
    name: github-repository-secret
