apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openapi-server-spring
  labels:
    app: openapi-server-spring
spec:
  interval: 5m
  path: ./manifests/overlays/development
  prune: true
  sourceRef:
    kind: GitRepository
    name: openapi-server-spring
  timeout: 2m
  wait: true
