apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: openapi-server-spring
  labels:
    app: openapi-server-spring
spec:
  groups:
    - name: ./example.rules
      rules:
        - alert: ExampleAlert
          expr: vector(1)
