apiVersion: v1
kind: Service
metadata:
  name: openapi-server-spring
  labels:
    app: openapi-server-spring
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: openapi-server-spring