apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: openapi-server-spring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openapi-server-spring
  endpoints:
  - port: http
