name: PR Validation

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Compile TypeScript
        run: npm run compile

      - name: Synthesize CDK8s
        run: npm run synth

      - name: Check generated files
        run: |
          if [ ! -f "dist/platform.k8s.yaml" ]; then
            echo "Error: CDK8s synthesis did not generate expected output file"
            exit 1
          fi
          echo "CDK8s synthesis successful - platform.k8s.yaml generated"

      - name: Upload PR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pr-kubernetes-manifests
          path: dist/
          retention-days: 3